apiVersion: v1
kind: Service
metadata:
  name: capstone-project-load-balancer
  labels:
    app: capstone-project
spec:
  type: LoadBalancer
  selector:
    app: capstone-project
  ports:
    - port: 80
      targetPort: 80